import type { Metadata } from 'next';
import { Flowbite, ThemeModeScript } from 'flowbite-react';
import { Inter } from 'next/font/google';
import './globals.css';
import MainNavbar from '@/components/Layouts/MainNavbar';
import flowbiteTheme from '../../flowbite-theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <ThemeModeScript />
            </head>
            <body className={inter.className}>
                <Flowbite theme={{theme: flowbiteTheme}}>
                    <MainNavbar />
                    {children}
                </Flowbite>
            </body>
        </html>
    );
}
